//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int ActivityLogID { get; set; }
        public int IdentityID { get; set; }
        public string ClientMachineName { get; set; }
        public System.DateTime AuthenticationTime { get; set; }
        public int ActivityCode { get; set; }
        public System.DateTime ActivityTime { get; set; }
        public string ActivityModule { get; set; }
        public string ActivityMessage { get; set; }
    }
}
