//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int AssetID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public bool Unlive { get; set; }
        public short AssetType { get; set; }
        public short AssetFlags { get; set; }
        public System.DateTime AssetWriteTime { get; set; }
        public System.DateTime LastSelectedTime { get; set; }
        public int FileSizeInBytes { get; set; }
        public int OwnerCalendarID { get; set; }
        public string DisplayName { get; set; }
        public string FileExtension { get; set; }
        public string Facets { get; set; }
        public int EventTypeID { get; set; }
        public int AssetDefID { get; set; }
    }
}
