//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CacheTimeBlockAtom
    {
        public long TimeBlockID { get; set; }
        public int FieldDefID { get; set; }
        public byte[] AtomHash { get; set; }
    }
}
