//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CacheSearchItem
    {
        public long TimeBlockID { get; set; }
        public System.DateTime TimeBlockWriteTime { get; set; }
        public System.DateTime LastWriteTime { get; set; }
        public string SearchText { get; set; }
    }
}
