//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calendar()
        {
            this.CalendarTimeBlocks = new HashSet<CalendarTimeBlock>();
            this.Digests = new HashSet<Digest>();
            this.ExternalStores = new HashSet<ExternalStore>();
            this.Gemischens = new HashSet<Gemischen>();
            this.Gemischens1 = new HashSet<Gemischen>();
            this.Members = new HashSet<Member>();
        }
    
        public int CalendarID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public bool Unlive { get; set; }
        public short CalendarFlags { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public int OwnerIdentityID { get; set; }
        public byte WeekBegins { get; set; }
        public byte DayDisplayBegins { get; set; }
        public byte DayDisplayEnds { get; set; }
        public string Keywords { get; set; }
        public string Location { get; set; }
        public string Region { get; set; }
        public short CalendarTimeZoneCode { get; set; }
        public short TempestViewVersion { get; set; }
        public string TempestViewSettings { get; set; }
    
        public virtual Identity Identity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalendarTimeBlock> CalendarTimeBlocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Digest> Digests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalStore> ExternalStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gemischen> Gemischens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gemischen> Gemischens1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual WebName WebName { get; set; }
    }
}
