//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeedTimeBlock
    {
        public int PubCalendarID { get; set; }
        public short TimeBlockDeed { get; set; }
        public long TimeBlockID { get; set; }
        public short TimeBlockDeedFlags { get; set; }
        public int DeedCount { get; set; }
        public System.DateTime LastDeedTime { get; set; }
        public int SnapshotDeedCount { get; set; }
        public System.DateTime SnapshotTime { get; set; }
    }
}
