//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailJob()
        {
            this.EmailDrops = new HashSet<EmailDrop>();
            this.EmailJobTimeBlocks = new HashSet<EmailJobTimeBlock>();
            this.EmailReminders = new HashSet<EmailReminder>();
        }
    
        public long EmailJobID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public short EmailJobType { get; set; }
        public short EmailJobFlags { get; set; }
        public short EmailJobState { get; set; }
        public System.DateTime EmailJobDateTime { get; set; }
        public int SubmitterIdentityID { get; set; }
        public System.Guid QueueUniqueID { get; set; }
        public string Message { get; set; }
        public short Format { get; set; }
        public Nullable<int> CalendarID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailDrop> EmailDrops { get; set; }
        public virtual EmailJobQuick EmailJobQuick { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailJobTimeBlock> EmailJobTimeBlocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailReminder> EmailReminders { get; set; }
    }
}
