//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public short PaymentType { get; set; }
        public int InvoiceID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime ReceivedTime { get; set; }
        public string AuthCode { get; set; }
        public short PaymentDataVersion { get; set; }
        public string PaymentData { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
