//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurrenceCatalog
    {
        public long TimeBlockID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public long MasterTimeBlockID { get; set; }
        public System.DateTime OriginalDate { get; set; }
    
        public virtual TimeBlock TimeBlock { get; set; }
        public virtual TimeBlock TimeBlock1 { get; set; }
    }
}
