//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sku
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sku()
        {
            this.InvoiceItems = new HashSet<InvoiceItem>();
        }
    
        public int SkuID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public short SkuRule { get; set; }
        public string SkuName { get; set; }
        public string SkuDescription { get; set; }
        public string SkuIdentifier { get; set; }
        public decimal CurrentPrice { get; set; }
        public System.DateTime AvailabilityStartTime { get; set; }
        public System.DateTime AvailabilityEndTime { get; set; }
        public int OwnerCalendarID { get; set; }
        public int VendorID { get; set; }
        public string Facets { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
    }
}
