//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SnapshotCustomer
    {
        public int SnapshotID { get; set; }
        public System.DateTime SnapshotTime { get; set; }
        public int CustomerID { get; set; }
        public short AccountType { get; set; }
        public short AccountState { get; set; }
        public short AccountFlags { get; set; }
        public short EnabledFeatures { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public short CustomerFlags { get; set; }
        public short AccountCredits { get; set; }
        public short NumPublishers { get; set; }
        public short NumEditors { get; set; }
        public short NumBilledAsPublishers { get; set; }
        public short NumBilledAsEditors { get; set; }
        public string CustomInvoice { get; set; }
    }
}
