//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpudsServedByCustomer
    {
        public int MonthNumber { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> TempestPageViews { get; set; }
        public Nullable<int> TotalSpudsBilled { get; set; }
        public Nullable<int> TotalSpudsServed { get; set; }
    }
}
