//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatCalendarReport
    {
        public int HourNumber { get; set; }
        public int CalendarID { get; set; }
        public short ReportType { get; set; }
        public int TempestPageViews { get; set; }
        public int TotalSessions { get; set; }
        public string Report { get; set; }
    }
}
