//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatTimeBlockCount
    {
        public int CalendarID { get; set; }
        public short TimeBlockCountType { get; set; }
        public System.DateTime ScanTime { get; set; }
        public int Cm9 { get; set; }
        public int Cm4 { get; set; }
        public int Cm3 { get; set; }
        public int Cm2 { get; set; }
        public int Cm1 { get; set; }
        public int Cm0 { get; set; }
        public int C00 { get; set; }
        public int C01 { get; set; }
        public int C02 { get; set; }
        public int C03 { get; set; }
        public int C04 { get; set; }
        public int C05 { get; set; }
        public int C06 { get; set; }
        public int C07 { get; set; }
        public int C08 { get; set; }
        public int C09 { get; set; }
        public int C10 { get; set; }
        public int C11 { get; set; }
        public int C12 { get; set; }
        public int C99 { get; set; }
    }
}
