//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatCalendarTimeBlock
    {
        public int CalendarID { get; set; }
        public int Startm99Tm30 { get; set; }
        public int Startm30T000 { get; set; }
        public int Start000T030 { get; set; }
        public int Start030T090 { get; set; }
        public int Start090T360 { get; set; }
        public int Start360T999 { get; set; }
        public int Endm30T999 { get; set; }
        public int Reminderm99T000 { get; set; }
        public int Reminder000T030 { get; set; }
        public int Reminder030T999 { get; set; }
        public int OtherReminderm99T000 { get; set; }
        public int OtherReminder000T030 { get; set; }
        public int OtherReminder030T999 { get; set; }
    }
}
