//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeBlockEmail
    {
        public long TimeBlockID { get; set; }
        public short EmailJobType { get; set; }
        public int RecipientIdentityID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public int Anticipation { get; set; }
        public int PubCalendarID { get; set; }
        public short SentState { get; set; }
        public System.DateTime SentTime { get; set; }
        public string Facets { get; set; }
    
        public virtual Identity Identity { get; set; }
        public virtual TimeBlock TimeBlock { get; set; }
    }
}
