//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeBlock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeBlock()
        {
            this.CalendarTimeBlocks = new HashSet<CalendarTimeBlock>();
            this.ExternalUniqueIDs = new HashSet<ExternalUniqueID>();
            this.IdentityTimeBlocks = new HashSet<IdentityTimeBlock>();
            this.RecurrenceCatalogs = new HashSet<RecurrenceCatalog>();
            this.TimeBlockEmails = new HashSet<TimeBlockEmail>();
        }
    
        public long TimeBlockID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public short TimeBlockType { get; set; }
        public bool Unlive { get; set; }
        public short TimeBlockFlags { get; set; }
        public int OwnerCalendarID { get; set; }
        public System.DateTime ContentWriteTime { get; set; }
        public System.DateTime TimeWriteTime { get; set; }
        public System.DateTime DescriptionWriteTime { get; set; }
        public System.DateTime NoteWriteTime { get; set; }
        public System.DateTime LocationWriteTime { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public string Location { get; set; }
        public string InfoUrl { get; set; }
        public string Facets { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalendarTimeBlock> CalendarTimeBlocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalUniqueID> ExternalUniqueIDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdentityTimeBlock> IdentityTimeBlocks { get; set; }
        public virtual RecurrenceCatalog RecurrenceCatalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecurrenceCatalog> RecurrenceCatalogs { get; set; }
        public virtual RecurrencePattern RecurrencePattern { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeBlockEmail> TimeBlockEmails { get; set; }
    }
}
