//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCalendarTimeBlockWithTime
    {
        public int CalendarID { get; set; }
        public long TimeBlockID { get; set; }
        public short CalendarTimeBlockFlags { get; set; }
        public short TimeBlockType { get; set; }
        public short TimeBlockFlags { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    }
}
