//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIdentityPassword
    {
        public int IdentityID { get; set; }
        public short IdentityFlags { get; set; }
        public string EmailAddress { get; set; }
        public short AccountFlags { get; set; }
        public short EnabledFeatures { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
    }
}
