//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLocalStoreInfoIdentity
    {
        public string Name { get; set; }
        public short LocalStoreInfoFlags { get; set; }
        public int SchemaVersion { get; set; }
        public int DatabaseID { get; set; }
        public int IdentityID { get; set; }
        public short IdentityFlags { get; set; }
        public short AccountFlags { get; set; }
        public short EnabledFeatures { get; set; }
        public short AccountTimeZoneCode { get; set; }
    }
}
