//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int IdentityID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public short AccountType { get; set; }
        public short AccountState { get; set; }
        public short AccountFlags { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public System.DateTime RefundDate { get; set; }
        public short EnabledFeatures { get; set; }
        public int ViewCalendarID { get; set; }
        public System.DateTime DisplayUpdatesAfter { get; set; }
        public short AccountTimeZoneCode { get; set; }
        public byte DefaultReminderChannel { get; set; }
        public byte DefaultReminderAnticipation { get; set; }
        public int EmailNotificationIdentityID { get; set; }
        public short EmailNotificationFormat { get; set; }
        public Nullable<int> SMSIdentityID { get; set; }
        public string BetaBuddy { get; set; }
        public string TrackerInfo { get; set; }
        public System.DateTime TrackerLandingTime { get; set; }
        public short AccountOrigin { get; set; }
        public short PendingActionVersion { get; set; }
        public string PendingAction { get; set; }
        public string Facets { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Identity Identity { get; set; }
    }
}
