//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeedAccountEdit
    {
        public int IdentityID { get; set; }
        public System.DateTime AccountEditTime { get; set; }
        public int AccountEditCount { get; set; }
        public System.DateTime AuthAnyTime { get; set; }
        public int AuthAnyCount { get; set; }
        public System.DateTime AuthSyncTime { get; set; }
        public int AuthSyncCount { get; set; }
        public System.DateTime UpdatesLastSeen { get; set; }
    }
}
