//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeedCalendarContent
    {
        public int CalendarID { get; set; }
        public System.DateTime LatestRowWriteTime { get; set; }
        public System.DateTime LatestContentWriteTime { get; set; }
        public System.DateTime WebViewTime { get; set; }
        public int WebViewCount { get; set; }
        public System.DateTime WebViewZeroTime { get; set; }
        public int WebViewZeroCount { get; set; }
    }
}
