//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailDrop
    {
        public long EmailJobID { get; set; }
        public int IdentityID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public short EmailDropState { get; set; }
        public System.DateTime EmailDropDateTime { get; set; }
        public int BounceErrorCode { get; set; }
    
        public virtual EmailJob EmailJob { get; set; }
    }
}
