//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalStore()
        {
            this.ExternalUniqueIDs = new HashSet<ExternalUniqueID>();
        }
    
        public int ExternalStoreID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public int CalendarID { get; set; }
        public int IdentityID { get; set; }
        public short ExternalStoreType { get; set; }
        public string StoreKey { get; set; }
        public string DisplayName { get; set; }
    
        public virtual Calendar Calendar { get; set; }
        public virtual Identity Identity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalUniqueID> ExternalUniqueIDs { get; set; }
    }
}
