//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalAccount
    {
        public short ExternalAccountType { get; set; }
        public string ExternalAccountID { get; set; }
        public int ExternalEntityID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public int IdentityID { get; set; }
        public short ExternalAccountFlags { get; set; }
        public int SignInCount { get; set; }
        public string OriginalEmailAddress { get; set; }
        public string Facets { get; set; }
    }
}
