//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldDef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FieldDef()
        {
            this.EventTypeFieldDefs = new HashSet<EventTypeFieldDef>();
        }
    
        public int FieldDefID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public short FieldType { get; set; }
        public int OwnerCalendarID { get; set; }
        public short FieldDefFlags { get; set; }
        public bool Unlive { get; set; }
        public short FieldDefType { get; set; }
        public string Facets { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTypeFieldDef> EventTypeFieldDefs { get; set; }
    }
}
