//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityTimeBlock
    {
        public long TimeBlockID { get; set; }
        public int IdentityID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public short IdentityTimeBlockFlags { get; set; }
        public bool Unlive { get; set; }
        public System.DateTime ContentWriteTime { get; set; }
        public System.DateTime InvitationStatusWriteTime { get; set; }
        public System.DateTime ResponseStatusWriteTime { get; set; }
        public byte InvitationStatus { get; set; }
        public byte ResponseStatus { get; set; }
        public string Facets { get; set; }
    
        public virtual Identity Identity { get; set; }
        public virtual TimeBlock TimeBlock { get; set; }
    }
}
