//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int CalendarID { get; set; }
        public int IdentityID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public bool Unlive { get; set; }
        public short MemberFlags { get; set; }
        public short CalendarColor { get; set; }
        public short ViewTemplate { get; set; }
        public short ViewTimeZoneCode { get; set; }
    
        public virtual Calendar Calendar { get; set; }
        public virtual Identity Identity { get; set; }
    }
}
