//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateBag
    {
        public int IdentityID { get; set; }
        public System.Guid StateGuid { get; set; }
        public short StateBagState { get; set; }
        public System.DateTime ExpirationDateTime { get; set; }
        public string StateBag1 { get; set; }
    }
}
