//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Storm11Entities : DbContext
    {
        public Storm11Entities()
            : base("name=Storm11Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountPref> AccountPrefs { get; set; }
        public virtual DbSet<AccountRequest> AccountRequests { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<Atom> Atoms { get; set; }
        public virtual DbSet<CacheAssetAtom> CacheAssetAtoms { get; set; }
        public virtual DbSet<CacheAssetSearchItem> CacheAssetSearchItems { get; set; }
        public virtual DbSet<CacheAssetWriteTime> CacheAssetWriteTimes { get; set; }
        public virtual DbSet<CacheFieldDefID> CacheFieldDefIDs { get; set; }
        public virtual DbSet<CacheFieldFilterItem> CacheFieldFilterItems { get; set; }
        public virtual DbSet<CacheFilterSetting> CacheFilterSettings { get; set; }
        public virtual DbSet<CacheIndexItem> CacheIndexItems { get; set; }
        public virtual DbSet<CacheSearchItem> CacheSearchItems { get; set; }
        public virtual DbSet<CacheTimeBlockAtom> CacheTimeBlockAtoms { get; set; }
        public virtual DbSet<CacheTimeBlockWriteTime> CacheTimeBlockWriteTimes { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
        public virtual DbSet<CalendarTimeBlock> CalendarTimeBlocks { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DeedAccountEdit> DeedAccountEdits { get; set; }
        public virtual DbSet<DeedCalendarContent> DeedCalendarContents { get; set; }
        public virtual DbSet<DeedCalendar> DeedCalendars { get; set; }
        public virtual DbSet<DeedTimeBlock> DeedTimeBlocks { get; set; }
        public virtual DbSet<Digest> Digests { get; set; }
        public virtual DbSet<EmailDrop> EmailDrops { get; set; }
        public virtual DbSet<EmailJobQuick> EmailJobQuicks { get; set; }
        public virtual DbSet<EmailJob> EmailJobs { get; set; }
        public virtual DbSet<EmailJobTimeBlock> EmailJobTimeBlocks { get; set; }
        public virtual DbSet<EmailProblem> EmailProblems { get; set; }
        public virtual DbSet<EmailReminder> EmailReminders { get; set; }
        public virtual DbSet<EventTypeFieldDef> EventTypeFieldDefs { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<ExternalAccount> ExternalAccounts { get; set; }
        public virtual DbSet<ExternalStore> ExternalStores { get; set; }
        public virtual DbSet<ExternalUniqueID> ExternalUniqueIDs { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<FieldDefOverride> FieldDefOverrides { get; set; }
        public virtual DbSet<FieldDef> FieldDefs { get; set; }
        public virtual DbSet<Gemischen> Gemischens { get; set; }
        public virtual DbSet<Identity> Identities { get; set; }
        public virtual DbSet<IdentityIdentity> IdentityIdentities { get; set; }
        public virtual DbSet<IdentityTimeBlock> IdentityTimeBlocks { get; set; }
        public virtual DbSet<InvoiceItem> InvoiceItems { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Ordinal> Ordinals { get; set; }
        public virtual DbSet<OutlookAppointment> OutlookAppointments { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Password> Passwords { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<RecurrenceCatalog> RecurrenceCatalogs { get; set; }
        public virtual DbSet<RecurrencePattern> RecurrencePatterns { get; set; }
        public virtual DbSet<Remittance> Remittances { get; set; }
        public virtual DbSet<Sku> Skus { get; set; }
        public virtual DbSet<SnapshotCustomer> SnapshotCustomers { get; set; }
        public virtual DbSet<SpudsServedByCustomer> SpudsServedByCustomers { get; set; }
        public virtual DbSet<StatCalendarReport> StatCalendarReports { get; set; }
        public virtual DbSet<StatCalendarTimeBlock> StatCalendarTimeBlocks { get; set; }
        public virtual DbSet<StateBag> StateBags { get; set; }
        public virtual DbSet<StatTimeBlockCount> StatTimeBlockCounts { get; set; }
        public virtual DbSet<TimeBlockEmail> TimeBlockEmails { get; set; }
        public virtual DbSet<TimeBlock> TimeBlocks { get; set; }
        public virtual DbSet<TransactionLog> TransactionLogs { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<WebName> WebNames { get; set; }
        public virtual DbSet<WriteTime> WriteTimes { get; set; }
        public virtual DbSet<LocalStoreInfo> LocalStoreInfoes { get; set; }
        public virtual DbSet<VAccessibleCalendar> VAccessibleCalendars { get; set; }
        public virtual DbSet<VCalendarTimeBlockWithTime> VCalendarTimeBlockWithTimes { get; set; }
        public virtual DbSet<VIdentityPassword> VIdentityPasswords { get; set; }
        public virtual DbSet<VLocalStoreInfoIdentity> VLocalStoreInfoIdentities { get; set; }
        public virtual DbSet<VMember> VMembers { get; set; }
        public virtual DbSet<VTimeBlockEmailsSendTime> VTimeBlockEmailsSendTimes { get; set; }
    }
}
