//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public int TransactionLogID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime WriteTime { get; set; }
        public int WriterIdentityID { get; set; }
        public short TransactionType { get; set; }
        public short Result { get; set; }
        public string ProviderTransactionID { get; set; }
        public int IdentityID { get; set; }
        public int CalendarID { get; set; }
        public int TimeBlockID { get; set; }
        public string TimeBlockDescription { get; set; }
        public System.DateTime TimeBlockStartDateTime { get; set; }
        public decimal ItemTotal { get; set; }
        public decimal TaxTotal { get; set; }
        public string Currency { get; set; }
        public short PaymentProviderType { get; set; }
        public int PaymentIdentityID { get; set; }
        public string IdentityName { get; set; }
        public string IdentityEmail { get; set; }
        public string Facets { get; set; }
        public int CustomerID { get; set; }
        public string CalendarDisplayName { get; set; }
        public int AttendeeCount { get; set; }
        public decimal PrepaidFee { get; set; }
    }
}
