//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTimeBlockEmailsSendTime
    {
        public Nullable<System.DateTime> SendTime { get; set; }
        public long TimeBlockID { get; set; }
        public int PubCalendarID { get; set; }
        public short EmailJobType { get; set; }
        public int RecipientIdentityID { get; set; }
    }
}
